# Generated by Django 3.1.7 on 2021-06-17 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Library_App', '0004_books_avail_book_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Id_Card',
            field=models.ImageField(default='', upload_to='profiles/'),
        ),
    ]
